# Site settings
title: 
header-img: img/home-bg.png
email: samrey2018@gmail.com
copyright_name: EPIC448
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  EPIC448
learn_profile: EPIC448
email_username: samrey2018@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
