# Site settings
author: Samuel.Ogundiran
title: Techuture
header-img: img/home-bg.png
email: samrey2018@gmail.com
copyright_name: Samuel.Ogundiran
description: > # this means to ignore newlines until "baseurl:"
  A Slice of  Technology Meets The  Future/ Array of Other Topics
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  EPIC448

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
